[package]
name = "arguments-parser"
version = "0.1.0"
authors = ["Kamil Pawlaczyk <prgmr.kamil.pawlaczyk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
